name: json_dynamic_widget_workspace
publish_to: none

environment:
  sdk: '>=3.5.0 <4.0.0'

dependency_overrides:
  analyzer: ^8.0.0
  build: ^4.0.2
  source_gen: ^4.0.2

workspace:
  - packages/annotation
  - packages/codegen
  - packages/json_dynamic_widget
  - packages/json_dynamic_widget/example
